root: true
env:
  browser: true
  es2020: true
  node: true
extends:
  - eslint:recommended
  - eslint-config-prettier
parserOptions:
  ecmaVersion: latest
  parser: babel-eslint
  sourceType: module
  createDefaultProgram: true
