
var Module = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(Module) {
  Module = Module || {};


var d;d||(d=typeof Module !== 'undefined' ? Module : {});var aa,p;d.ready=new Promise(function(b,a){aa=b;p=a});var ba=Object.assign({},d),ca="object"==typeof window,q="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,t="",u,v;
if(ea){const {createRequire:b}=await import("module");var require=b(import.meta.url),fs=require("fs"),fa=require("path");q?t=fa.dirname(t)+"/":t=require("url").fileURLToPath(new URL("./",import.meta.url));u=(a,c)=>{a=a.startsWith("file://")?new URL(a):fa.normalize(a);return fs.readFileSync(a,c?void 0:"utf8")};v=a=>{a=u(a,!0);a.buffer||(a=new Uint8Array(a));return a};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);process.on("uncaughtException",
function(a){throw a;});process.on("unhandledRejection",function(a){throw a;});d.inspect=function(){return"[Emscripten Module object]"}}else if(ca||q)q?t=self.location.href:"undefined"!=typeof document&&document.currentScript&&(t=document.currentScript.src),_scriptDir&&(t=_scriptDir),0!==t.indexOf("blob:")?t=t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1):t="",u=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.send(null);return a.responseText},q&&(v=b=>{var a=new XMLHttpRequest;a.open("GET",
b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)});d.print||console.log.bind(console);var w=d.printErr||console.warn.bind(console);Object.assign(d,ba);ba=null;var x;d.wasmBinary&&(x=d.wasmBinary);var noExitRuntime=d.noExitRuntime||!0;"object"!=typeof WebAssembly&&y("no native wasm support detected");var z,ha=!1,ia="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ja(b,a,c){var f=a+c;for(c=a;b[c]&&!(c>=f);)++c;if(16<c-a&&b.buffer&&ia)return ia.decode(b.subarray(a,c));for(f="";a<c;){var e=b[a++];if(e&128){var h=b[a++]&63;if(192==(e&224))f+=String.fromCharCode((e&31)<<6|h);else{var g=b[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|b[a++]&63;65536>e?f+=String.fromCharCode(e):(e-=65536,f+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else f+=String.fromCharCode(e)}return f}var A,B,C,D,E,G,H,ka,la;
function ma(){var b=z.buffer;A=b;d.HEAP8=B=new Int8Array(b);d.HEAP16=D=new Int16Array(b);d.HEAP32=G=new Int32Array(b);d.HEAPU8=C=new Uint8Array(b);d.HEAPU16=E=new Uint16Array(b);d.HEAPU32=H=new Uint32Array(b);d.HEAPF32=ka=new Float32Array(b);d.HEAPF64=la=new Float64Array(b)}var I,na=[],oa=[],pa=[];function qa(){var b=d.preRun.shift();na.unshift(b)}function ra(b){pa.unshift(b)}var J=0,K=null,L=null;
function y(b){if(d.onAbort)d.onAbort(b);b="Aborted("+b+")";w(b);ha=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");p(b);throw b;}function sa(){return M.startsWith("data:application/octet-stream;base64,")}var M;if(d.locateFile){if(M="markdown.wasm",!sa()){var ta=M;M=d.locateFile?d.locateFile(ta,t):t+ta}}else M=(new URL("markdown.wasm",import.meta.url)).href;
function ua(){var b=M;try{if(b==M&&x)return new Uint8Array(x);if(v)return v(b);throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}function va(){return x||!ca&&!q||"function"!=typeof fetch?Promise.resolve().then(function(){return ua()}):fetch(M,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+M+"'";return b.arrayBuffer()}).catch(function(){return ua()})}function N(b){for(;0<b.length;)b.shift()(d)}
function P(b){switch(b){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+b);}}var wa=void 0;function Q(b){for(var a="";C[b];)a+=wa[C[b++]];return a}var R={},xa={},ya={};function za(b,a){if(void 0===b)b="_unknown";else{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var c=b.charCodeAt(0);b=48<=c&&57>=c?"_"+b:b}return(new Function("body","return function "+b+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(a)}
function Aa(b){var a=Error,c=za(b,function(f){this.name=b;this.message=f;f=Error(f).stack;void 0!==f&&(this.stack=this.toString()+"\n"+f.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Ba=void 0;function S(b){throw new Ba(b);}
function T(b,a,c={}){if(!("argPackAdvance"in a))throw new TypeError("registerType registeredInstance requires argPackAdvance");var f=a.name;b||S('type "'+f+'" must have a positive integer typeid pointer');if(xa.hasOwnProperty(b)){if(c.B)return;S("Cannot register type '"+f+"' twice")}xa[b]=a;delete ya[b];R.hasOwnProperty(b)&&(a=R[b],delete R[b],a.forEach(e=>e()))}
var U=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}],Ca=b=>{switch(b){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var a=U.length?U.pop():V.length;V[a]={C:1,value:b};return a}};function Da(b){return this.fromWireType(G[b>>2])}function Ea(b,a){switch(a){case 2:return function(c){return this.fromWireType(ka[c>>2])};case 3:return function(c){return this.fromWireType(la[c>>3])};default:throw new TypeError("Unknown float type: "+b);}}
function Fa(b,a,c){switch(a){case 0:return c?function(f){return B[f]}:function(f){return C[f]};case 1:return c?function(f){return D[f>>1]}:function(f){return E[f>>1]};case 2:return c?function(f){return G[f>>2]}:function(f){return H[f>>2]};default:throw new TypeError("Unknown integer type: "+b);}}var Ga="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function Ha(b,a){var c=b>>1;for(var f=c+a/2;!(c>=f)&&E[c];)++c;c<<=1;if(32<c-b&&Ga)return Ga.decode(C.subarray(b,c));c="";for(f=0;!(f>=a/2);++f){var e=D[b+2*f>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Ia(b,a,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var f=a;c=c<2*b.length?c/2:b.length;for(var e=0;e<c;++e)D[a>>1]=b.charCodeAt(e),a+=2;D[a>>1]=0;return a-f}function Ja(b){return 2*b.length}
function Ka(b,a){for(var c=0,f="";!(c>=a/4);){var e=G[b+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,f+=String.fromCharCode(55296|e>>10,56320|e&1023)):f+=String.fromCharCode(e)}return f}function La(b,a,c){void 0===c&&(c=2147483647);if(4>c)return 0;var f=a;c=f+c-4;for(var e=0;e<b.length;++e){var h=b.charCodeAt(e);if(55296<=h&&57343>=h){var g=b.charCodeAt(++e);h=65536+((h&1023)<<10)|g&1023}G[a>>2]=h;a+=4;if(a+4>c)break}G[a>>2]=0;return a-f}
function Ma(b){for(var a=0,c=0;c<b.length;++c){var f=b.charCodeAt(c);55296<=f&&57343>=f&&++c;a+=4}return a}for(var W=void 0,Na=[],Oa=Array(256),X=0;256>X;++X)Oa[X]=String.fromCharCode(X);wa=Oa;Ba=d.BindingError=Aa("BindingError");d.InternalError=Aa("InternalError");d.count_emval_handles=function(){for(var b=0,a=5;a<V.length;++a)void 0!==V[a]&&++b;return b};d.get_first_emval=function(){for(var b=5;b<V.length;++b)if(void 0!==V[b])return V[b];return null};
var Qa={i:function(){},j:function(b,a,c,f,e){var h=P(c);a=Q(a);T(b,{name:a,fromWireType:function(g){return!!g},toWireType:function(g,k){return k?f:e},argPackAdvance:8,readValueFromPointer:function(g){if(1===c)var k=B;else if(2===c)k=D;else if(4===c)k=G;else throw new TypeError("Unknown boolean type size: "+a);return this.fromWireType(k[g>>h])},A:null})},h:function(b,a){a=Q(a);T(b,{name:a,fromWireType:function(c){c||S("Cannot use deleted val. handle = "+c);var f=V[c].value;4<c&&0===--V[c].C&&(V[c]=
void 0,U.push(c));return f},toWireType:function(c,f){return Ca(f)},argPackAdvance:8,readValueFromPointer:Da,A:null})},e:function(b,a,c){c=P(c);a=Q(a);T(b,{name:a,fromWireType:function(f){return f},toWireType:function(f,e){return e},argPackAdvance:8,readValueFromPointer:Ea(a,c),A:null})},b:function(b,a,c,f,e){a=Q(a);-1===e&&(e=4294967295);e=P(c);var h=k=>k;if(0===f){var g=32-8*c;h=k=>k<<g>>>g}c=a.includes("unsigned")?function(k,l){return l>>>0}:function(k,l){return l};T(b,{name:a,fromWireType:h,toWireType:c,
argPackAdvance:8,readValueFromPointer:Fa(a,e,0!==f),A:null})},a:function(b,a,c){function f(h){h>>=2;var g=H;return new e(A,g[h+1],g[h])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][a];c=Q(c);T(b,{name:c,fromWireType:f,argPackAdvance:8,readValueFromPointer:f},{B:!0})},d:function(b,a){a=Q(a);var c="std::string"===a;T(b,{name:a,fromWireType:function(f){var e=H[f>>2],h=f+4;if(c)for(var g=h,k=0;k<=e;++k){var l=h+k;if(k==e||0==C[l]){g=g?ja(C,g,l-g):
"";if(void 0===m)var m=g;else m+=String.fromCharCode(0),m+=g;g=l+1}}else{m=Array(e);for(k=0;k<e;++k)m[k]=String.fromCharCode(C[h+k]);m=m.join("")}Y(f);return m},toWireType:function(f,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var h,g="string"==typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||S("Cannot pass non-string to std::string");if(c&&g){var k=0;for(h=0;h<e.length;++h){var l=e.charCodeAt(h);127>=l?k++:2047>=l?k+=2:55296<=l&&57343>=l?(k+=4,++h):
k+=3}h=k}else h=e.length;k=Pa(4+h+1);l=k+4;H[k>>2]=h;if(c&&g){if(g=l,l=h+1,h=C,0<l){l=g+l-1;for(var m=0;m<e.length;++m){var n=e.charCodeAt(m);if(55296<=n&&57343>=n){var r=e.charCodeAt(++m);n=65536+((n&1023)<<10)|r&1023}if(127>=n){if(g>=l)break;h[g++]=n}else{if(2047>=n){if(g+1>=l)break;h[g++]=192|n>>6}else{if(65535>=n){if(g+2>=l)break;h[g++]=224|n>>12}else{if(g+3>=l)break;h[g++]=240|n>>18;h[g++]=128|n>>12&63}h[g++]=128|n>>6&63}h[g++]=128|n&63}}h[g]=0}}else if(g)for(g=0;g<h;++g)m=e.charCodeAt(g),255<
m&&(Y(l),S("String has UTF-16 code units that do not fit in 8 bits")),C[l+g]=m;else for(g=0;g<h;++g)C[l+g]=e[g];null!==f&&f.push(Y,k);return k},argPackAdvance:8,readValueFromPointer:Da,A:function(f){Y(f)}})},c:function(b,a,c){c=Q(c);if(2===a){var f=Ha;var e=Ia;var h=Ja;var g=()=>E;var k=1}else 4===a&&(f=Ka,e=La,h=Ma,g=()=>H,k=2);T(b,{name:c,fromWireType:function(l){for(var m=H[l>>2],n=g(),r,F=l+4,O=0;O<=m;++O){var da=l+4+O*a;if(O==m||0==n[da>>k])F=f(F,da-F),void 0===r?r=F:(r+=String.fromCharCode(0),
r+=F),F=da+a}Y(l);return r},toWireType:function(l,m){"string"!=typeof m&&S("Cannot pass non-string to C++ string type "+c);var n=h(m),r=Pa(4+n+a);H[r>>2]=n>>k;e(m,r+4,n+a);null!==l&&l.push(Y,r);return r},argPackAdvance:8,readValueFromPointer:Da,A:function(l){Y(l)}})},k:function(b,a){a=Q(a);T(b,{D:!0,name:a,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},g:function(b,a,c){C.copyWithin(b,a,a+c)},f:function(b){var a=C.length;b>>>=0;if(2147483648<b)return!1;for(var c=1;4>=c;c*=2){var f=
a*(1+.2/c);f=Math.min(f,b+100663296);var e=Math;f=Math.max(b,f);e=e.min.call(e,2147483648,f+(65536-f%65536)%65536);a:{try{z.grow(e-A.byteLength+65535>>>16);ma();var h=1;break a}catch(g){}h=void 0}if(h)return!0}return!1}};
(function(){function b(e){d.asm=e.exports;z=d.asm.l;ma();I=d.asm.t;oa.unshift(d.asm.m);J--;d.monitorRunDependencies&&d.monitorRunDependencies(J);0==J&&(null!==K&&(clearInterval(K),K=null),L&&(e=L,L=null,e()))}function a(e){b(e.instance)}function c(e){return va().then(function(h){return WebAssembly.instantiate(h,f)}).then(function(h){return h}).then(e,function(h){w("failed to asynchronously prepare wasm: "+h);y(h)})}var f={a:Qa};J++;d.monitorRunDependencies&&d.monitorRunDependencies(J);if(d.instantiateWasm)try{return d.instantiateWasm(f,
b)}catch(e){w("Module.instantiateWasm callback failed with error: "+e),p(e)}(function(){return x||"function"!=typeof WebAssembly.instantiateStreaming||sa()||ea||"function"!=typeof fetch?c(a):fetch(M,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,f).then(a,function(h){w("wasm streaming compile failed: "+h);w("falling back to ArrayBuffer instantiation");return c(a)})})})().catch(p);return{}})();
d.___wasm_call_ctors=function(){return(d.___wasm_call_ctors=d.asm.m).apply(null,arguments)};d._wrealloc=function(){return(d._wrealloc=d.asm.n).apply(null,arguments)};d._wfree=function(){return(d._wfree=d.asm.o).apply(null,arguments)};var Y=d._free=function(){return(Y=d._free=d.asm.p).apply(null,arguments)};d._WErrGetCode=function(){return(d._WErrGetCode=d.asm.q).apply(null,arguments)};d._WErrGetMsg=function(){return(d._WErrGetMsg=d.asm.r).apply(null,arguments)};
d._WErrClear=function(){return(d._WErrClear=d.asm.s).apply(null,arguments)};d._parseUTF8=function(){return(d._parseUTF8=d.asm.u).apply(null,arguments)};var Pa=d._malloc=function(){return(Pa=d._malloc=d.asm.v).apply(null,arguments)};d.___getTypeName=function(){return(d.___getTypeName=d.asm.w).apply(null,arguments)};d.__embind_initialize_bindings=function(){return(d.__embind_initialize_bindings=d.asm.x).apply(null,arguments)};d.UTF8ArrayToString=ja;d.addOnPostRun=ra;
d.addFunction=function(b,a){if(!W){W=new WeakMap;var c=I.length;if(W)for(var f=0;f<0+c;f++){var e=I.get(f);e&&W.set(e,f)}}if(W.has(b))return W.get(b);if(Na.length)c=Na.pop();else{try{I.grow(1)}catch(k){if(!(k instanceof RangeError))throw k;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}c=I.length-1}try{I.set(c,b)}catch(k){if(!(k instanceof TypeError))throw k;if("function"==typeof WebAssembly.Function){f=WebAssembly.Function;e={i:"i32",j:"i32",f:"f32",d:"f64",p:"i32"};for(var h={parameters:[],
results:"v"==a[0]?[]:[e[a[0]]]},g=1;g<a.length;++g)h.parameters.push(e[a[g]]),"j"===a[g]&&h.parameters.push("i32");a=new f(h,b)}else{f=[1];e=a.slice(0,1);a=a.slice(1);h={i:127,p:127,j:126,f:125,d:124};f.push(96);g=a.length;128>g?f.push(g):f.push(g%128|128,g>>7);for(g=0;g<a.length;++g)f.push(h[a[g]]);"v"==e?f.push(0):f.push(1,h[e]);a=[0,97,115,109,1,0,0,0,1];e=f.length;128>e?a.push(e):a.push(e%128|128,e>>7);a.push.apply(a,f);a.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);a=new WebAssembly.Module(new Uint8Array(a));
a=(new WebAssembly.Instance(a,{e:{f:b}})).exports.f}I.set(c,a)}W.set(b,c);return c};d.removeFunction=function(b){W.delete(I.get(b));Na.push(b)};var Z;L=function Ra(){Z||Sa();Z||(L=Ra)};
function Sa(){function b(){if(!Z&&(Z=!0,d.calledRun=!0,!ha)){N(oa);aa(d);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;)ra(d.postRun.shift());N(pa)}}if(!(0<J)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)qa();N(na);0<J||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);b()},1)):b())}}
if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();Sa();


  return Module.ready
}
);
})();
export default Module;