async function Module(moduleArg={}){var Module=moduleArg;var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,f=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";if(f){let {createRequire:a}=await import(/* @vite-ignore */("node:"+"module"));var g=a(import.meta.url)}var h=(a,b)=>{throw b;},k=import.meta.url,l="",m,n;if(f){var p=g("node:fs");k.startsWith("file:")&&(l=g("node:path").dirname(g("node:url").fileURLToPath(k))+"/");n=a=>{a=q(a)?new URL(a):a;return p.readFileSync(a)};m=async a=>{a=q(a)?new URL(a):a;return p.readFileSync(a,void 0)};
process.argv.slice(2);h=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{l=(new URL(".",k)).href}catch{}m=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}console.log.bind(console);var r=console.error.bind(console),t=!1,u,q=a=>a.startsWith("file://");function v(){if(!w?.buffer?.resizable){var a=x.buffer;Module.HEAP8=w=new Int8Array(a);Module.HEAP16=y=new Int16Array(a);Module.HEAPU8=z=new Uint8Array(a);Module.HEAPU16=
A=new Uint16Array(a);Module.HEAP32=B=new Int32Array(a);Module.HEAPU32=C=new Uint32Array(a);Module.HEAPF32=D=new Float32Array(a);Module.HEAPF64=E=new Float64Array(a);Module.HEAP64=F=new BigInt64Array(a);Module.HEAPU64=G=new BigUint64Array(a)}}function H(a){a=`Aborted(${a})`;r(a);t=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var I;async function ca(a){try{var b=await m(a);return new Uint8Array(b)}catch{}if(n)a=n(a);else throw"both async and sync fetching of the wasm failed";
return a}async function da(a,b){try{var c=await ca(a);return await WebAssembly.instantiate(c,b)}catch(d){r(`failed to asynchronously prepare wasm: ${d}`),H(d)}}async function ea(a){var b=I;if(!f)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){r(`wasm streaming compile failed: ${d}`),r("falling back to ArrayBuffer instantiation")}return da(b,a)}class J{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=
a}}var y,B,F,w,D,E,A,C,G,z,K=a=>{for(;a.length>0;)a.shift()(Module)},L=()=>H(""),fa=0,ha=()=>{fa=0},M={},ia=a=>{if(a instanceof J||a=="unwind")return u;h(1,a)},N=a=>{u=a;h(a,new J(a))},ja=a=>{u=a;N(a)},ka=a=>{if(!t)try{return a()}catch(b){ia(b)}finally{}},ma=(a,b)=>{M[a]&&(clearTimeout(M[a].id),delete M[a]);if(!b)return 0;var c=setTimeout(()=>{delete M[a];ka(()=>la(a,performance.now()))},b);M[a]={id:c,u:b};return 0},na=a=>{a=(a-x.buffer.byteLength+65535)/65536|0;try{return x.grow(a),v(),1}catch(b){}},
oa=a=>{var b=z.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);if(na(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)))return!0}return!1},O=[],Q=a=>{var b=O[a];b||(O[a]=b=P.get(a));return b},pa=(a,b)=>{if(S)for(var c=a;c<a+b;c++){var d=Q(c);d&&S.set(d,c)}},S,qa=a=>{S||(S=new WeakMap,pa(0,P.length));return S.get(a)||0},T=[],ra=()=>T.length?T.pop():P.grow(1),U=(a,b)=>{P.set(a,b);O[a]=P.get(a)},V=a=>{var b=a.length;return[b%128|128,b>>
7,...a]},sa={i:127,p:127,j:126,f:125,d:124,e:111},W=a=>V(Array.from(a,b=>sa[b])),ua=(a,b)=>{b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...V([1,96,...W(b.slice(1)),...W(b[0]==="v"?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);return(new WebAssembly.Instance(b,{e:{f:a}})).exports.f},va=(a,b)=>{var c=qa(a);if(c)return c;c=ra();try{U(c,a)}catch(d){if(!(d instanceof TypeError))throw d;b=ua(a,b);U(c,b)}S.set(a,c);return c},wa=a=>{S.delete(Q(a));U(a,null);T.push(a)},X=[],xa=a=>
X.push(a),Y=globalThis.TextDecoder&&new TextDecoder,ya=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},za=(a,b=0,c,d)=>{c=ya(a,b,c,d);if(c-b>16&&a.buffer&&Y)return Y.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var R=a[b++]&63;if((e&224)==192)d+=String.fromCharCode((e&31)<<6|R);else{var ta=a[b++]&63;e=(e&240)==224?(e&15)<<12|R<<6|ta:(e&7)<<18|R<<12|ta<<6|a[b++]&63;e<65536?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=
String.fromCharCode(e)}return d};Module.addOnPostRun=xa;Module.addFunction=va;Module.removeFunction=wa;Module.UTF8ArrayToString=za;Module.ExitStatus=J;Module.HEAP16=y;Module.HEAP32=B;Module.HEAP64=F;Module.HEAP8=w;Module.HEAPF32=D;Module.HEAPF64=E;Module.HEAPU16=A;Module.HEAPU32=C;Module.HEAPU64=G;Module.HEAPU8=z;Module.callRuntimeCallbacks=K;Module.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return w[a];case "i8":return w[a];case "i16":return y[a>>1];case "i32":return B[a>>
2];case "i64":return F[a>>3];case "float":return D[a>>2];case "double":return E[a>>3];case "*":return C[a>>2];default:H(`invalid type for getValue: ${b}`)}};Module.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":w[a]=b;break;case "i8":w[a]=b;break;case "i16":y[a>>1]=b;break;case "i32":B[a>>2]=b;break;case "i64":F[a>>3]=BigInt(b);break;case "float":D[a>>2]=b;break;case "double":E[a>>3]=b;break;case "*":C[a>>2]=b;break;default:H(`invalid type for setValue: ${c}`)}};Module.stackRestore=
a=>Aa(a);Module.stackSave=()=>Ba();Module.__abort_js=L;Module.__emscripten_runtime_keepalive_clear=ha;Module.runtimeKeepaliveCounter=fa;Module.__setitimer_js=ma;Module.timers=M;Module.clearTimers=()=>{for(var a of Object.values(M))clearTimeout(a.id)};Module.callUserCallback=ka;Module.handleException=ia;Module.maybeExit=()=>{};Module._exit=ja;Module.exitJS=ja;Module._proc_exit=N;Module.keepRuntimeAlive=()=>!0;Module._emscripten_get_now=()=>performance.now();Module._emscripten_resize_heap=oa;Module.getHeapMax=
()=>2147483648;Module.alignMemory=(a,b)=>Math.ceil(a/b)*b;Module.growMemory=na;Module.ptrToString=function(a){return"0x"+(a>>>0).toString(16).padStart(8,"0")};Module.addFunction=va;Module.getFunctionAddress=qa;Module.updateTableMap=pa;Module.getWasmTableEntry=Q;Module.wasmTableMirror=O;Module.functionsInTableMap=S;Module.getEmptyTableSlot=ra;Module.freeTableIndexes=T;Module.setWasmTableEntry=U;Module.convertJsFunctionToWasm=ua;Module.uleb128EncodeWithLen=V;Module.generateTypePack=W;Module.wasmTypeCodes=
sa;Module.removeFunction=wa;Module.addOnPostRun=xa;Module.onPostRuns=X;Module.UTF8ArrayToString=za;Module.UTF8Decoder=Y;Module.findStringEnd=ya;var la,Aa,Ba,x,P,Ca={e:L,d:ha,a:ma,b:oa,c:N},Z;Z=await (async function(){var a={a:Ca};I??=Module.locateFile?l+"markdown.wasm":(new URL("markdown.wasm",import.meta.url)).href;a=Z=(await ea(a)).instance.exports;Module._wrealloc=a.h;Module._wfree=a.i;Module._WErrGetCode=a.j;Module._WErrGetMsg=a.k;Module._WErrClear=a.l;Module._parseUTF8=a.m;la=Module.__emscripten_timeout=
a.o;Aa=Module.__emscripten_stack_restore=a.p;Module.__emscripten_stack_alloc=a.q;Ba=Module._emscripten_stack_get_current=a.r;Module.memory=x=a.f;Module.__indirect_function_table=P=a.n;v();return Z}());await (async function(){t||(Z.g(),K(X))}());;return Module}export default Module;
