
var Module = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(Module = {})  {

var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa,p;e.ready=new Promise((a,b)=>{aa=a;p=b});var ba=Object.assign({},e),r="";"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src);_scriptDir&&(r=_scriptDir);0!==r.indexOf("blob:")?r=r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):r="";var t=e.printErr||console.error.bind(console);Object.assign(e,ba);ba=null;var u;e.wasmBinary&&(u=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;
"object"!=typeof WebAssembly&&v("no native wasm support detected");var w,ca=!1,x,y,z,A,B,C,da,ea;function fa(){var a=w.buffer;e.HEAP8=x=new Int8Array(a);e.HEAP16=z=new Int16Array(a);e.HEAP32=B=new Int32Array(a);e.HEAPU8=y=new Uint8Array(a);e.HEAPU16=A=new Uint16Array(a);e.HEAPU32=C=new Uint32Array(a);e.HEAPF32=da=new Float32Array(a);e.HEAPF64=ea=new Float64Array(a)}var D,ha=[],ia=[],ja=[];function ka(){var a=e.preRun.shift();ha.unshift(a)}function la(a){ja.unshift(a)}var E=0,F=null,H=null;
function v(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";t(a);ca=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");p(a);throw a;}function ma(a){return a.startsWith("data:application/octet-stream;base64,")}var I;if(e.locateFile){if(I="markdown.wasm",!ma(I)){var na=I;I=e.locateFile?e.locateFile(na,r):r+na}}else I=(new URL("markdown.wasm",import.meta.url)).href;
function oa(a){try{if(a==I&&u)return new Uint8Array(u);throw"both async and sync fetching of the wasm failed";}catch(b){v(b)}}function pa(a){return u||"function"!=typeof fetch?Promise.resolve().then(()=>oa(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>oa(a))}
function qa(a,b,c){return pa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{t("failed to asynchronously prepare wasm: "+d);v(d)})}function ra(a,b){var c=I;return u||"function"!=typeof WebAssembly.instantiateStreaming||ma(c)||"function"!=typeof fetch?qa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){t("wasm streaming compile failed: "+f);t("falling back to ArrayBuffer instantiation");return qa(c,a,b)}))}
function J(a){for(;0<a.length;)a.shift()(e)}function K(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError(`Unknown type size: ${a}`);}}var sa=void 0;function L(a){for(var b="";y[a];)b+=sa[y[a++]];return b}var M={},ta={},ua={};function va(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a}function wa(a,b){a=va(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function xa(a){var b=Error,c=wa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c}var ya=void 0;function N(a){throw new ya(a);}
function P(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||N(`type "${d}" must have a positive integer typeid pointer`);if(ta.hasOwnProperty(a)){if(c.H)return;N(`Cannot register type '${d}' twice`)}ta[a]=b;delete ua[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(f=>f()))}
var Q=new function(){this.A=[void 0];this.C=[];this.get=function(a){return this.A[a]};this.has=function(a){return void 0!==this.A[a]};this.F=function(a){var b=this.C.pop()||this.A.length;this.A[b]=a;return b};this.G=function(a){this.A[a]=void 0;this.C.push(a)}},za=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return Q.F({I:1,value:a})}};function R(a){return this.fromWireType(B[a>>2])}
function Aa(a,b){switch(b){case 2:return function(c){return this.fromWireType(da[c>>2])};case 3:return function(c){return this.fromWireType(ea[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Ba(a,b,c){switch(b){case 0:return c?function(d){return x[d]}:function(d){return y[d]};case 1:return c?function(d){return z[d>>1]}:function(d){return A[d>>1]};case 2:return c?function(d){return B[d>>2]}:function(d){return C[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Ca="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Da(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var g=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|g:(f&7)<<18|h<<12|g<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
var Ea="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function Fa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&A[c];)++c;c<<=1;if(32<c-a&&Ea)return Ea.decode(y.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var f=z[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c}function Ga(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)z[b>>1]=a.charCodeAt(f),b+=2;z[b>>1]=0;return b-d}function Ha(a){return 2*a.length}
function Ia(a,b){for(var c=0,d="";!(c>=b/4);){var f=B[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function Ja(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var g=a.charCodeAt(++f);h=65536+((h&1023)<<10)|g&1023}B[b>>2]=h;b+=4;if(b+4>c)break}B[b>>2]=0;return b-d}
function Ka(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var S=[];function La(a){var b=S[a];b||(a>=S.length&&(S.length=a+1),S[a]=b=D.get(a));return b}for(var T=void 0,U=[],Ma=Array(256),V=0;256>V;++V)Ma[V]=String.fromCharCode(V);sa=Ma;ya=e.BindingError=xa("BindingError");e.InternalError=xa("InternalError");Q.A.push({value:void 0},{value:null},{value:!0},{value:!1});Q.D=Q.A.length;
e.count_emval_handles=function(){for(var a=0,b=Q.D;b<Q.A.length;++b)void 0!==Q.A[b]&&++a;return a};
var Na={i:function(){},j:function(a,b,c,d,f){var h=K(c);b=L(b);P(a,{name:b,fromWireType:function(g){return!!g},toWireType:function(g,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(g){if(1===c)var k=x;else if(2===c)k=z;else if(4===c)k=B;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[g>>h])},B:null})},h:function(a,b){b=L(b);P(a,{name:b,fromWireType:function(c){c||N("Cannot use deleted val. handle = "+c);var d=Q.get(c).value;c>=Q.D&&0===--Q.get(c).I&&
Q.G(c);return d},toWireType:function(c,d){return za(d)},argPackAdvance:8,readValueFromPointer:R,B:null})},d:function(a,b,c){c=K(c);b=L(b);P(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){return f},argPackAdvance:8,readValueFromPointer:Aa(b,c),B:null})},b:function(a,b,c,d,f){b=L(b);-1===f&&(f=4294967295);f=K(c);var h=k=>k;if(0===d){var g=32-8*c;h=k=>k<<g>>>g}c=b.includes("unsigned")?function(k,l){return l>>>0}:function(k,l){return l};P(a,{name:b,fromWireType:h,toWireType:c,argPackAdvance:8,
readValueFromPointer:Ba(b,f,0!==d),B:null})},a:function(a,b,c){function d(h){h>>=2;var g=C;return new f(g.buffer,g[h+1],g[h])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=L(c);P(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{H:!0})},e:function(a,b){b=L(b);var c="std::string"===b;P(a,{name:b,fromWireType:function(d){var f=C[d>>2],h=d+4;if(c)for(var g=h,k=0;k<=f;++k){var l=h+k;if(k==f||0==y[l]){g=g?Da(y,g,l-g):"";if(void 0===
m)var m=g;else m+=String.fromCharCode(0),m+=g;g=l+1}}else{m=Array(f);for(k=0;k<f;++k)m[k]=String.fromCharCode(y[h+k]);m=m.join("")}W(d);return m},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var h,g="string"==typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||N("Cannot pass non-string to std::string");var k;if(c&&g)for(h=k=0;h<f.length;++h){var l=f.charCodeAt(h);127>=l?k++:2047>=l?k+=2:55296<=l&&57343>=l?(k+=4,++h):k+=3}else k=
f.length;h=k;k=X(4+h+1);l=k+4;C[k>>2]=h;if(c&&g){if(g=l,l=h+1,h=y,0<l){l=g+l-1;for(var m=0;m<f.length;++m){var n=f.charCodeAt(m);if(55296<=n&&57343>=n){var q=f.charCodeAt(++m);n=65536+((n&1023)<<10)|q&1023}if(127>=n){if(g>=l)break;h[g++]=n}else{if(2047>=n){if(g+1>=l)break;h[g++]=192|n>>6}else{if(65535>=n){if(g+2>=l)break;h[g++]=224|n>>12}else{if(g+3>=l)break;h[g++]=240|n>>18;h[g++]=128|n>>12&63}h[g++]=128|n>>6&63}h[g++]=128|n&63}}h[g]=0}}else if(g)for(g=0;g<h;++g)m=f.charCodeAt(g),255<m&&(W(l),N("String has UTF-16 code units that do not fit in 8 bits")),
y[l+g]=m;else for(g=0;g<h;++g)y[l+g]=f[g];null!==d&&d.push(W,k);return k},argPackAdvance:8,readValueFromPointer:R,B:function(d){W(d)}})},c:function(a,b,c){c=L(c);if(2===b){var d=Fa;var f=Ga;var h=Ha;var g=()=>A;var k=1}else 4===b&&(d=Ia,f=Ja,h=Ka,g=()=>C,k=2);P(a,{name:c,fromWireType:function(l){for(var m=C[l>>2],n=g(),q,G=l+4,O=0;O<=m;++O){var Z=l+4+O*b;if(O==m||0==n[Z>>k])G=d(G,Z-G),void 0===q?q=G:(q+=String.fromCharCode(0),q+=G),G=Z+b}W(l);return q},toWireType:function(l,m){"string"!=typeof m&&
N(`Cannot pass non-string to C++ string type ${c}`);var n=h(m),q=X(4+n+b);C[q>>2]=n>>k;f(m,q+4,n+b);null!==l&&l.push(W,q);return q},argPackAdvance:8,readValueFromPointer:R,B:function(l){W(l)}})},k:function(a,b){b=L(b);P(a,{J:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},g:function(a,b,c){y.copyWithin(a,b,b+c)},f:function(a){var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var f=Math,h=f.min;d=Math.max(a,
d);d+=(65536-d%65536)%65536;a:{var g=w.buffer;try{w.grow(h.call(f,2147483648,d)-g.byteLength+65535>>>16);fa();var k=1;break a}catch(l){}k=void 0}if(k)return!0}return!1}};
(function(){function a(c){c=c.exports;e.asm=c;w=e.asm.l;fa();D=e.asm.w;ia.unshift(e.asm.m);E--;e.monitorRunDependencies&&e.monitorRunDependencies(E);if(0==E&&(null!==F&&(clearInterval(F),F=null),H)){var d=H;H=null;d()}return c}var b={a:Na};E++;e.monitorRunDependencies&&e.monitorRunDependencies(E);if(e.instantiateWasm)try{return e.instantiateWasm(b,a)}catch(c){t("Module.instantiateWasm callback failed with error: "+c),p(c)}ra(b,function(c){a(c.instance)}).catch(p);return{}})();
e._wrealloc=function(){return(e._wrealloc=e.asm.n).apply(null,arguments)};e._wfree=function(){return(e._wfree=e.asm.o).apply(null,arguments)};function W(){return(W=e.asm.p).apply(null,arguments)}e._WErrGetCode=function(){return(e._WErrGetCode=e.asm.q).apply(null,arguments)};e._WErrGetMsg=function(){return(e._WErrGetMsg=e.asm.r).apply(null,arguments)};e._WErrClear=function(){return(e._WErrClear=e.asm.s).apply(null,arguments)};e._parseUTF8=function(){return(e._parseUTF8=e.asm.t).apply(null,arguments)};
function X(){return(X=e.asm.u).apply(null,arguments)}e.__embind_initialize_bindings=function(){return(e.__embind_initialize_bindings=e.asm.v).apply(null,arguments)};e.addOnPostRun=la;
e.addFunction=function(a,b){if(!T){T=new WeakMap;var c=D.length;if(T)for(var d=0;d<0+c;d++){var f=La(d);f&&T.set(f,d)}}if(c=T.get(a)||0)return c;if(U.length)c=U.pop();else{try{D.grow(1)}catch(k){if(!(k instanceof RangeError))throw k;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}c=D.length-1}try{d=c,D.set(d,a),S[d]=D.get(d)}catch(k){if(!(k instanceof TypeError))throw k;if("function"==typeof WebAssembly.Function){d=WebAssembly.Function;f={i:"i32",j:"i64",f:"f32",d:"f64",p:"i32"};for(var h=
{parameters:[],results:"v"==b[0]?[]:[f[b[0]]]},g=1;g<b.length;++g)h.parameters.push(f[b[g]]);b=new d(h,a)}else{d=[1];f=b.slice(0,1);b=b.slice(1);h={i:127,p:127,j:126,f:125,d:124};d.push(96);g=b.length;128>g?d.push(g):d.push(g%128|128,g>>7);for(g=0;g<b.length;++g)d.push(h[b[g]]);"v"==f?d.push(0):d.push(1,h[f]);b=[0,97,115,109,1,0,0,0,1];f=d.length;128>f?b.push(f):b.push(f%128|128,f>>7);b.push.apply(b,d);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));b=(new WebAssembly.Instance(b,
{e:{f:a}})).exports.f}d=c;D.set(d,b);S[d]=D.get(d)}T.set(a,c);return c};e.removeFunction=function(a){T.delete(La(a));U.push(a)};e.UTF8ArrayToString=Da;var Y;H=function Oa(){Y||Pa();Y||(H=Oa)};
function Pa(){function a(){if(!Y&&(Y=!0,e.calledRun=!0,!ca)){J(ia);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)la(e.postRun.shift());J(ja)}}if(!(0<E)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)ka();J(ha);0<E||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();Pa();


  return Module.ready
}

);
})();
export default Module;